services:
  postgres:
    image: postgres:15-alpine
    container_name: stream_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stream_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  db-service:
    build: .
    container_name: go_db_service
    restart: on-failure
    depends_on:
      - postgres
    environment:
      - DATABASE_DSN=${DATABASE_DSN}
      - GRPC_PORT=${GRPC_PORT}
    ports:
      - "50051:50051"
    volumes:
      - ./certs:/app/certs:ro

volumes:
  postgres_data: